### ISSUE TITLE
.navbar-toggle button in .navbar-header seems to be not working

### ISSUE THREAD

**Issue by ipeinado** [Pushing7/gpii.net#5]
.navbar-toggle button in navbar-header is not working for small screens. It does not open the navbar-collapse menu.

**Comment by thegurf** [comment]
Thanks Ignacio. Enabling the bootstrap CDN in appearance settings fixed this for now, bu I'll need to do some digging to figure out why it wasn't working and to clean up some of the odd behaviors that are present now that the toggle button is working. 

Am expecting to totally rework this theme once we have a more finished design.

**Comment by ipeinado** [comment]
Enabling the bootstrap CDN worked. Thanks!
